language: python

jobs:
  include:
    - os: osx
      osx_image: xcode11.6
      env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
      language: generic

install:
  - bash ./.travis_before_install.sh $URL
  - echo $(which samtools)
  - echo $(samtools --version)
  - echo $(which Trinity)
  - echo $(Trinity --version)
  - echo $(which fastq-dump)
  - echo $(fastq-dump --version)

script:
  - r2g --dry-run
