language: python

jobs:
  include:
  - os: linux
    dist: bionic
    env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    python: "3.8"
  - os: linux
    dist: bionic
    env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    python: "3.7"
  - os: linux
    dist: xenial
    env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    python: "3.6"
  - os: osx
    osx_image: xcode12
    env: URL=https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    language: generic

before_install:
  - |-
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install libxml-libxml-perl
      fi
  - bash ./.travis_before_install.sh $URL
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          export "PATH=$PATH:$PWD/miniconda3/bin"
        ;;
        osx)
          export "PATH=$PWD/miniconda3/bin:$PWD/trinityrnaseq-v${TRINITY}:$PATH"
          export "TRINITY_HOME=$PWD/trinityrnaseq-v${TRINITY}"
        ;;
      esac

install:
  - pip install .[test]

script:
  - travis_wait 20 pytest --cov=r2g
 
after_success:
  - codecov
