{% set name = "r2g" %}
{% set version = "1.0.4" %}

package:
  # name: "{{ name|lower }}"
  name: r2g.dev
  version: "{{ version }}"

source:
  url: "https://test.pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c4f5a9af00256b01587b02925fb847592063122ac6e7fdb8688b58280af1167c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [osx]

requirements:
  host:
    - pip
    - python >=3.6
    - requests >=2.24.0,<2.25
    - selenium >=3.141.0,<3.142
  run:
    - python >=3.6
    - requests >=2.24.0,<2.25
    - selenium >=3.141.0,<3.142
    - sra-tools
    - trinity =2.8.5
    - samtools >=1.9
    - numpy

test:
  imports:
    - r2g
    - r2g.local
    - r2g.online
    - r2g.utils

about:
  home: "https://yangwu91.github.io/r2g/"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A computationally lightweight and homology-based pipeline that allows rapid identification of genes or gene families from raw sequence databases in the absence of an assembly"
  doc_url: "https://github.com/yangwu91/r2g/wiki"
  dev_url: "https://github.com/yangwu91/r2g.git"

extra:
  recipe-maintainers:
    - yangwu91

