name: Run a quick test on macOS using brewsci Formula

on:
  push

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up brewsci Tap
      env:
        URL_BASE: "https://test.pypi.org/"
        PRIVATE_WEBDRIVER: ${{ secrets.PRIVATE_WEBDRIVER }}
        #URL_BASE: "https://pypi.io"
      run: |
        brew tap brewsci/bio
        export VERSION=$(grep -o "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9a-z]+" src/r2g/__init__.py)
        export URL="${URL_BASE}/packages/source/r/r2g/r2g-${VERSION}.tar.gz"
        sed -i "s/  url \"http.+\"/  url \"${URL}\"/" brewsci-Formula/r2g.rb
        export URL="${URL_BASE}/packages/source/r/r2g/r2g-${VERSION}.tar.gz"
        wget -qO r2g-tmp.tar.gz $URL
        export SHA=$(sha256sum r2g-tmp.tar.gz |cut -f 1 -d " ")
        sed -i "s/  sha256 \"[0-9a-z]\{64\}\"/  sha256 \"${SHA}\"/" brewsci-Formula/r2g.rb
        cat ./brewsci-Formula/r2g.rb
        cp ./brewsci-Formula/r2g.rb /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/
        brew install r2g
        r2g --dry-run
