name: Run a quick test using Docker on Windows

on:
  repository_dispatch:
    types: [trigger-dryrun-docker]

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Docker image and run a quick test
      run : |
        where docker
        DockerCli.exe -SwitchLinuxEngine
        docker pull yangwu91/r2g.docker.test:latest
        docker run yangwu91/r2g.docker.test:latest --dry-run
      shell: cmd
