name: Run a quick test on macOS using brewsci Formula

on:
  push

jobs:
  deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up brewsci Tap and run a quick test
      env:
        URL_BASE: "https://test.pypi.org/"
        PRIVATE_WEBDRIVER: ${{ secrets.PRIVATE_WEBDRIVER }}
        #URL_BASE: "https://pypi.io"
      run: |
        brew tap brewsci/bio
        export VERSION=$(grep -o "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9a-z]\+" src/r2g/__init__.py)
        export URL="${URL_BASE}/packages/source/r/r2g/r2g-${VERSION}.tar.gz"
        sed -i ".1" "s,^  url \"http.+\"$,  url \"${URL}\"," brewsci-Formula/r2g.rb
        export URL="${URL_BASE}/packages/source/r/r2g/r2g-${VERSION}.tar.gz"
        wget -qO r2g-tmp.tar.gz $URL
        export SHA=$(shasum -a 256 r2g-tmp.tar.gz |cut -f 1 -d " ")
        sed -i ".2" "s/^  sha256 \"[0-9a-z]\{64\}\"$/  sha256 \"${SHA}\"/" brewsci-Formula/r2g.rb
        cp ./brewsci-Formula/r2g.rb /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/
        cat /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/r2g.rb
        brew install r2g
        mkdir -p "${HOME}"/.ncbi
        cat > "${HOME}"/.ncbi/user-settings.mkfg <<_EOF
        ## auto-generated configuration file - DO NOT EDIT ##

        /LIBS/GUID = "$(uuidgen)"
        /config/default = "false"
        /repository/user/ad/public/apps/file/volumes/flatAd = "."
        /repository/user/ad/public/apps/refseq/volumes/refseqAd = "."
        /repository/user/ad/public/apps/sra/volumes/sraAd = "."
        /repository/user/ad/public/apps/sraPileup/volumes/ad = "."
        /repository/user/ad/public/apps/sraRealign/volumes/ad = "."
        /repository/user/ad/public/root = "."
        /repository/user/default-path = "${HOME}/ncbi"

        _EOF
        r2g --dry-run
