name: Run a quick test using Docker on Windows

on:
  push

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull Docker image and run a quick test 1
      run : |
        Set-Content -Value "`{`"experimental`":true`}" -Path C:\ProgramData\docker\config\daemon.json
        restart-service docker
        winpty docker run hello-world
        winpty docker run -it hello-world
        docker pull yangwu91/r2g.docker.test:latest
        winpty docker run -it --platform=linux yangwu91/r2g.docker.test:latest --dry-run
      shell: powershell
#    - name: Pull Docker image and run a quick test 2
#      run: |
#        tree "c:\Program Files\Docker"
#        "c:\Program Files\Docker\DockerCli.exe" -SwitchLinuxEngine
#        docker pull yangwu91/r2g.docker.test:latest
#        docker run -it yangwu91/r2g.docker.test:latest --dry-run
#      shell: cmd
