name: Run a quick test using Docker on Windows

on:
  push

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Pull Docker image and run a quick test 1
#      run : |
#        Set-Content -Value "`{`"experimental`":true`}" -Path C:\ProgramData\docker\config\daemon.json
#        cd 'C:\Program Files\'
#        mkdir "Linux Containers"
#        cd '.\Linux Containers\'
#        curl -OutFile release.zip https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip
#        Expand-Archive -DestinationPath . .\release.zip
#        rm release.zip
#        docker pull yangwu91/r2g.docker.test:latest
#        docker run -it --platform=linux yangwu91/r2g.docker.test:latest --dry-run
#      shell: powershell
    - name: Pull Docker image and run a quick test 2
      run: |
        "c:\Program Files\Docker\DockerCli.exe" -SwitchLinuxEngine
        docker pull yangwu91/r2g.docker.test:latest
        docker run -it yangwu91/r2g.docker.test:latest --dry-run
      shell: cmd
